sudo: required
services:
  - docker

before_install:
  - docker build -t agrimolizzi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run agrimolizzi/react-test npm test -- --coverage

after_success:
  - docker build -t agrimolizzi/multi-client ./client
  - docker build -t agrimolizzi/multi-nginx ./nginx
  - docker build -t agrimolizzi/multi-server ./server
  - docker build -t agrimolizzi/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push agrimolizzi/multi-client
  - docker push agrimolizzi/multi-nginx
  - docker push agrimolizzi/multi-server
  - docker push agrimolizzi/multi-worker

